import type { DigestData } from "./types.js";
import { formatDate, formatNumber } from "./utils.js";

/** Pure transformation: DigestData -> human-readable Markdown report. */
export function renderMarkdown(digest: DigestData): string {
  const { account, totals } = digest;
  const lines: string[] = [];

  lines.push(`# GitHub Digest: ${account.login}`);
  lines.push("");
  lines.push(
    `${account.type} account · ${formatNumber(account.publicRepos)} public repos · digest window: last ${digest.windowDays} days · generated ${formatDate(digest.generatedAt)}`,
  );
  lines.push("");

  lines.push("## Headline stats");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|---|---|");
  lines.push(`| Total repos | ${formatNumber(totals.totalRepos)} |`);
  lines.push(`| Total stars | ${formatNumber(totals.totalStars)} |`);
  lines.push(`| Total forks | ${formatNumber(totals.totalForks)} |`);
  lines.push(`| Total open issues | ${formatNumber(totals.totalOpenIssues)} |`);
  lines.push(`| New issues (window) | ${formatNumber(totals.newIssues)} |`);
  lines.push(`| New PRs (window) | ${formatNumber(totals.newPRs)} |`);
  lines.push(`| Repos published to npm | ${formatNumber(totals.reposWithNpmPackage)} |`);
  lines.push(`| Combined npm weekly downloads | ${formatNumber(totals.totalWeeklyNpmDownloads)} |`);
  lines.push("");

  lines.push("## Most active repos");
  lines.push("");
  if (digest.mostActiveRepos.length === 0) {
    lines.push("_No repos found._");
  } else {
    lines.push("| Repo | Stars | Forks | Open issues | Last push | npm weekly downloads |");
    lines.push("|---|---|---|---|---|---|");
    for (const r of digest.mostActiveRepos) {
      const downloads = r.npm?.isPublished && typeof r.npm.weeklyDownloads === "number" ? formatNumber(r.npm.weeklyDownloads) : "—";
      lines.push(
        `| [${r.name}](${r.htmlUrl}) | ${formatNumber(r.stars)} | ${formatNumber(r.forks)} | ${formatNumber(r.openIssues)} | ${formatDate(r.pushedAt)} | ${downloads} |`,
      );
    }
  }
  lines.push("");

  lines.push("## Top npm packages by weekly downloads");
  lines.push("");
  if (digest.topDownloaded.length === 0) {
    lines.push("_No published npm packages found among these repos._");
  } else {
    lines.push("| Package | Latest version | Weekly downloads | Repo |");
    lines.push("|---|---|---|---|");
    for (const r of digest.topDownloaded) {
      lines.push(
        `| [${r.npm.packageName}](${r.npm.npmUrl}) | ${r.npm.latestVersion ?? "—"} | ${formatNumber(r.npm.weeklyDownloads ?? 0)} | [${r.name}](${r.htmlUrl}) |`,
      );
    }
  }
  lines.push("");

  lines.push(`## Recent issues (last ${digest.windowDays} days)`);
  lines.push("");
  if (digest.recentIssues.length === 0) {
    lines.push("_No new issues in this window._");
  } else {
    for (const i of digest.recentIssues) {
      lines.push(`- [${i.repo}#${i.number}](${i.htmlUrl}) ${i.title} — opened by \`${i.author}\` on ${formatDate(i.createdAt)}`);
    }
  }
  lines.push("");

  lines.push(`## Recent pull requests (last ${digest.windowDays} days)`);
  lines.push("");
  if (digest.recentPRs.length === 0) {
    lines.push("_No new pull requests in this window._");
  } else {
    for (const p of digest.recentPRs) {
      lines.push(`- [${p.repo}#${p.number}](${p.htmlUrl}) ${p.title} — opened by \`${p.author}\` on ${formatDate(p.createdAt)}`);
    }
  }
  lines.push("");

  lines.push("---");
  lines.push(
    `_Generated by [portfolio-github-digest](https://github.com/AdamM510/portfolio-github-digest) — cross-referencing the GitHub REST API with the public npm registry. No credentials required to reproduce this report._`,
  );

  return lines.join("\n");
}
